openapi: 3.0.1
info:
  title: BalanceAPI
  description: API Definition of BalanceAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/accounts
paths:
  /{accountNumber}/balance:
    get:
      parameters:
      - name: accountNumber
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
